<?php

/**
 * @file
 * Contains proedm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function proedm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the proedm module.
    case 'help.page.proedm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Support Module for Prosperidad en Democracia') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function proedm_theme() {
  return [
    'proedm' => [
      'render element' => 'children',
    ],
  ];
}
